apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l4mco84jq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l4mco84jq-python 
  name: l4mco84jq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l4mco84jq-python 
