apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l4mco84jq-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-12bd7ed066.jy3d.p3.openshiftapps.com/rhtap/rhtap-qe-python:30e9a0c78db00794b16c836fce218a37738ecfae@sha256:bd87e73303187a43f99b8979d107ffefe283431490bd809ecef05b2289ff49a2
          name: container-image
